server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
      export:
        enabled: true
  health:
    refresh:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 5
        max-interval: 10000
        multiplier: 1.5
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_LB:lb://auth-service}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: JwtFilter
        - id: game-service
          uri: ${GAME_SERVICE_LB:lb://game-service}
          predicates:
            - Path=/api/v1/game/**
          filters:
            - name: JwtFilter
        - id: analytic-service
          uri: ${ANALYTIC_SERVICE_LB:lb://analytic-service}
          predicates:
            - Path=/api/v1/analytic/**
          filters:
            - name: JwtFilter
        - id: order-service
          uri: ${ORDER_SERVICE_LB:lb://order-service}
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: JwtFilter

logging:
  #  config: http://localhost:8088/log/logback.xml
  file:
    name: logs/ApiGateway-log.txt
  level:
    org.springframework.cloud.gateway: INFO
