name: CI - Analytics Service

on:
  push:
    paths:
      - 'Springboot_Microservices_Demo/backend/analytics-service/**'
      - '.github/workflows/ci-analytics-service.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.set-image-uri.outputs.image-uri }}

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name:  Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name:  Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name:  Set image URI
      id: set-image-uri
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        REGION=us-east-1
        IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/analytics-service:latest"
        echo " Image URI: $IMAGE_URI"
        echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT

    - name:  Build and Push Docker Image to ECR
      run: |
        docker build -t ${{ steps.set-image-uri.outputs.image-uri }} ./Springboot_Microservices_Demo/backend/analytics-service
        docker push ${{ steps.set-image-uri.outputs.image-uri }}

    - name:  Done
      run: echo "Successfully pushed: ${{ steps.set-image-uri.outputs.image-uri }}"
