name: CI - Analytics Service

on:
  push:
    paths:
      - 'Springboot_Microservices_Demo/analytics-service/**'
      - '.github/workflows/ci-analytics-service.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x ./builds/git_update.sh
          ./builds/git_update.sh -v patch

      - name: Set image URIs
        id: set-image-uri
        run: |
          ACCOUNT_ID="115771043725"
          REGION="us-east-1"
