name: CI - Analytics Service

on:
  push:
    paths:
      - 'Springboot_Microservices_Demo/analytics-service/**'
      - '.github/workflows/ci-analytics-service.yml'
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.set-image-uri.outputs.image-uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set image URI
      id: set-image-uri
      run: |
        IMAGE_URI="115771043725.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest"
        echo "Image URI: $IMAGE_URI"
        echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        echo "Building Docker image: ${{ steps.set-image-uri.outputs.image-uri }}"
        docker build -t ${{ steps.set-image-uri.outputs.image-uri }} ./Springboot_Microservices_Demo/analytics-service

    - name: Push Docker image to ECR
      run: |
        echo "Pushing Docker image: ${{ steps.set-image-uri.outputs.image-uri }}"
        docker push ${{ steps.set-image-uri.outputs.image-uri }}

    - name: Done
      run: echo "Successfully pushed: ${{ steps.set-image-uri.outputs.image-uri }}"
