name: CI - Analytics Service

on:
  push:
    paths:
      - 'Springboot_Microservices_Demo/analytics-service/**'
      - '.github/workflows/ci-analytics-service.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        IMAGE=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/analytics-service

        docker build -t $IMAGE:latest ./Springboot_Microservices_Demo/analytics-service
        docker push $IMAGE:latest
